version: '3.3'
services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "${FLASK_APP}"
    env_file: ".env"
    ports: 
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
  nginx:
    build:
      context: services/nginx
    ports:
      - "80:80"
