version: '3.3'
services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c 'flask run --host=0.0.0.0'
    ports: 
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
  nginx:
    build:
      context: services/nginx
    ports:
      - "80:80"
