FROM python:3.6
ENV PROJECT_ROOT /usr/src/app/

COPY requirements.txt $PROJECT_ROOT
COPY requirements.dev.txt $PROJECT_ROOT

WORKDIR $PROJECT_ROOT

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
