---
- hosts:
    webservers
  become: true
  remote_user: root

  tasks:
    - name: create network
      docker_network:
        name: default_network

    - name: download app image
      docker_image:
        name: krigar1184/workshop-devops-app:latest
        force: yes

    - name: download nginx image
      docker_image:
        name: krigar1184/workshop-devops-nginx:latest
        force: yes

    - name: run app
      docker_container:
        name: app
        image: krigar1184/workshop-devops-app:latest
        restart_policy: always
        recreate: yes
        state: started
        networks:
          - name: default_network
        ports:
          - "5000:5000"

    - name: run nginx
      docker_container: 
        name: nginx
        image: krigar1184/workshop-devops-nginx:latest
        state: started
        detach: yes
        restart_policy: always
        recreate: yes
        networks:
          - name: default_network
        ports:
          - "80:80"
